### ISSUE TITLE
getting error while testing deployment

### ISSUE THREAD

**Issue by INGourav** [FBoucher/SimpleDevBox#1]
Hi Sir,

I am getting below error while testing this deployment.

> PS C:\WINDOWS\system32> Test-AzureRmResourceGroupDeployment -ResourceGroupName GouravDevBOx -TemplateFile C:\Users\kumar
_g\Desktop\TestVMCHOCOEXtension.json

Code    : InvalidTemplateDeployment
Message : The template deployment '576a7307-8b4e-48ee-a4c3-fd700bcbca56' is not valid according to the validation
          procedure. The tracking id is 'cac6be54-91c3-4f2b-a4a2-c32d282e4eca'. See inner errors for details. Please
          see https://aka.ms/arm-deploy for usage details.
Details : {Microsoft.Azure.Commands.ResourceManager.Cmdlets.SdkModels.PSResourceManagerError}

This is the template that I am using to create VM

`{
    "$schema": "https://schema.management.azure.com/schemas/2015-01-01/deploymentTemplate.json#",
    "contentVersion": "1.0.0.0",
    "parameters": {},
    "variables": {
        "scripturl": "https://raw.githubusercontent.com/unpredictablegourav/AzureVMTest/master/Extesnsion.ps1"
    },
    "resources": [{
        "type": "Microsoft.Storage/storageAccounts",
        "apiVersion": "2018-07-01",
        "name": "[toLower('GouravDevBoxstorage')]",
        "location": "[resourceGroup().location]",
        "tags": {
            "displayName": "GouravDevBox Storage Account"
        },
        "properties": {
            "accountType": "Standard_LRS"
        }
    },
    {
        "apiVersion": "2018-08-01",
        "type": "Microsoft.Network/publicIPAddresses",
        "name": "GouravDevBox-PublicIP",
        "location": "[resourceGroup().location]",
        "tags": {
            "displayName": "PublicIPAddress"
        },
        "properties": {
            "publicIPAllocationMethod": "Dynamic",
            "dnsSettings": {
                "domainNameLabel": "[toLower('GouravDevBox')]"
            }
        }
    },
    {
        "apiVersion": "2018-08-01",
        "type": "Microsoft.Network/virtualNetworks",
        "name": "GouravDevBox-VirtualNetwork",
        "location": "[resourceGroup().location]",
        "tags": {
            "displayName": "VirtualNetwork"
        },
        "properties": {
            "addressSpace": {
                "addressPrefixes": [
                    "10.0.0.0/16"
                ]
            },
            "subnets": [
                {
                    "name": "GouravDevBox-VirtualNetwork-Subnet",
                    "properties": {
                        "addressPrefix": "10.0.0.0/24"
                    }
                }
            ]
        }
    },
    {
        "apiVersion": "2018-08-01",
        "type": "Microsoft.Network/networkInterfaces",
        "name": "GouravDevBox-NetworkInterface",
        "location": "[resourceGroup().location]",
        "dependsOn": [
            "Microsoft.Network/publicIPAddresses/GouravDevBox-PublicIP",
            "Microsoft.Network/virtualNetworks/GouravDevBox-VirtualNetwork"
        ],
        "tags": {
            "displayName": "GouravDevBox Network Interface"
        },
        "properties": {
            "ipConfigurations": [
                {
                    "name": "ipconfig1",
                    "properties": {
                        "privateIPAllocationMethod": "Dynamic",
                        "publicIPAddress": {
                            "id": "[resourceId('Microsoft.Network/publicIPAddresses', 'GouravDevBox-PublicIP')]"
                        },
                        "subnet": {
                            "id": "[concat(resourceId('Microsoft.Network/virtualNetworks', 'GouravDevBox-VirtualNetwork'), '/subnets/GouravDevBox-VirtualNetwork-Subnet')]"
                        }
                    }
                }
            ]
        }
    },
    {
        "apiVersion": "2018-10-01",
        "type": "Microsoft.Compute/virtualMachines",
        "name": "GouravDevBox",
        "location": "[resourceGroup().location]",
        "dependsOn": [
            "[concat('Microsoft.Storage/storageAccounts/', toLower('GouravDevBoxstorage'))]",
            "Microsoft.Network/networkInterfaces/GouravDevBox-NetworkInterface"
        ],
        "tags": {
            "displayName": "GouravDevBox"
        },
        "properties": {
            "hardwareProfile": {
                "vmSize": "Standard_A2"
            },
            "osProfile": {
                "computerName": "GouravDevBox",
                "adminUsername": "Gourav",
                "adminPassword": "GramSwan@1234567890"
            },
            "storageProfile": {
                "imageReference": {
                    "publisher": "MicrosoftWindowsServer",
                    "offer": "WindowsServer",
                    "sku": "2012-R2-Datacenter",
                    "version": "latest"
                },
                "osDisk": {
                    "createOption": "FromImage"
                }
            },
            "networkProfile": {
                "networkInterfaces": [
                    {
                        "id": "[resourceId('Microsoft.Network/networkInterfaces', 'GouravDevBox-NetworkInterface')]"
                    }
                ]
            },
            "diagnosticsProfile": {
                "bootDiagnostics": {
                    "enabled": true,
                    "storageUri": "[concat('http://', toLower('GouravDevBoxstorage'), '.blob.core.windows.net')]"
                }
            }
        },
        "resources": [
            {
                "apiVersion": "2018-06-01",
                "type": "extensions",
                "name": "config-app",
                "location": "[resourceGroup().location]",
                "dependsOn": [
                    "[concat('Microsoft.Compute/virtualMachines/', 'GouravDevBox')]"
                ],
                "tags": {
                    "displayName": "config-app"
                },
                "properties": {
                    "publisher": "Microsoft.Compute",
                    "type": "CustomScriptExtension",
                    "typeHandlerVersion": "1.9",
                    "autoUpgradeMinorVersion": true,
                    "settings": {
                        "fileUris": [
                            "[variables('scripturl')]"
                        ]
                    },
                    "protectedSettings": {
                        "commandToExecute": "[concat('powershell -ExecutionPolicy Unrestricted -File ', './Extesnsion.ps1')]"
                    }
                }
            }
        ]
    }],
    "outputs": {}
}`

**Comment by INGourav** [comment]
I found to solve this, There are api version that are not supported in some particular regions so I had this issue.
To check supported API version use below command: -

PowerShell : -  (Get-AzResourceProvider -ProviderNamespace "Microsoft.Compute").resourceTypes | Where-Object ResourceTypeName -eq "virtualMachines"

CLI: -az provider show -n "Microsoft.Compute" --query "resourceTypes[?resourceType == 'virtualMachines']"

**Comment by fboucher** [comment]
Thanks @unpredictablegourav I totally missed the error! I'm glad you find a workaround...
